name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: |
          yarn workspace webamp lint
          yarn workspace webamp-dot-org lint
          yarn workspace webamp type-check
          yarn workspace webamp-dot-org type-check
      - name: Build
        run: |
          yarn workspace webamp build
          yarn workspace webamp-dot-org build
          yarn workspace webamp build-library
      - name: Run Unit Tests
        run: |
          yarn workspace webamp test
          yarn workspace webamp-dot-org test
      - name: Run Integration Tests
        run: yarn workspace webamp-dot-org integration-tests
        env:
          CI: true
      - name: Upload Screenshot Diffs
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: image_diffs
          path: packages/webamp-dot-org/js/__tests__/__image_snapshots__/__diff_output__/
      - name: Generate New Screenshots
        if: failure()
        run: |
          yarn workspace webamp-dot-org integration-tests -u
      - name: Upload New Screenshots
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: new_images
          path: packages/webamp-dot-org/js/__tests__/__image_snapshots__/
